version: '3.8'

services:
  postgreSQL:
    image: postgres:16-alpine
    restart: no
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: lock_transactions
      POSTGRES_PASSWORD: admin123
